version: "3.8"
services:
  backend:
    image: "korayguney/gittigidiyor-fullstack:18.9.2021.9.32.19"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: prod