version: "3.8"
services:
  backend:
    image: "korayguney/gittigidiyor-fullstack:17.9.2021.19.16.7"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: prod